---
title: "Case Study Fires"
author: "Anna Talucci"
date: "2024-12-05"
output: html_document
---

# Packages
```{r}
library(tidyverse)
library(lubridate)
library(sf)
```


# Data
```{r}
cafires = st_read("../data/boundaries/firePerimeters/CanadaFires1986-2021.shp", "CanadaFires1986-2021")
```
```{r}
( fire554_yr2014 = cafires %>% filter(YEAR == 2014) %>% filter(NFIREID ==554) )
```
```{r}
( fire2927_yr2015 = cafires %>% filter(YEAR == 2015) %>% filter(NFIREID ==2927) )
```

```{r}
fire2019 = cafires %>% filter(YEAR == 2019) %>% filter(NFIREID ==177)
```

```{r}
fire2016 = cafires %>% filter(YEAR == 2016) %>% filter(NFIREID ==146)
```

```{r}
fire2018 = cafires %>% filter(YEAR == 2018) %>% filter(NFIREID ==567)
```

```{r}
unique(cafires$PRENAME) 
```

```{r}
sk2014_2018 = cafires %>% filter(YEAR %in% c(2014, 2015, 2016, 2017, 2018)) %>% filter(PRENAME=="Saskatchewan" )
```

```{r eval=FALSE, include=FALSE}
st_write(fire2016, "../outputs/spatialDataCreate/geopackage/caseStudyCanadafire2016.gpkg", layer = "fire2016")
```

```{r eval=FALSE, include=FALSE}
st_write(fire2018, "../outputs/spatialDataCreate/geopackage/caseStudyCanadafire2018.gpkg", layer = "fire2018")
```

```{r eval=FALSE, include=FALSE}
st_write(fire2019, "../outputs/spatialDataCreate/geopackage/caseStudyCanadafire2019.gpkg", layer = "fire2019")
```

```{r eval=FALSE, include=FALSE}
st_write(fire2927_yr2015, "../outputs/spatialDataCreate/shapefiles/CaseStudyCanada/caseStudyCanadafire2927_yr2015.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(fire554_yr2014, "../outputs/spatialDataCreate/shapefiles/CaseStudyCanada/caseStudyCanadafire554_yr2014.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(fire2016, "../outputs/spatialDataCreate/shapefiles/CaseStudyCanada/caseStudyCanadafire2016.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(fire2018, "../outputs/spatialDataCreate/shapefiles/CaseStudyCanada/caseStudyCanadafire2018.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(fire2019, "../outputs/spatialDataCreate/shapefiles/CaseStudyCanada/caseStudyCanadafire2019.shp", driver="ESRI Shapefile")
```

```{r eval=FALSE, include=FALSE}
st_write(sk2014_2018, "../outputs/spatialDataCreate/shapefiles/SKFires2014_2018.shp", driver="ESRI Shapefile")
```