---
title: "Landsat scenes Canada priority"
author: "Anna Talucci"
date: "2024-08-21"
output: html_document
---


# Overview

Prioritize Canadian Landsat Scenes for Angela's albedo processing.

# Packages

```{r}
library(sf)
library(tidyverse)
library(mapview)
```

# Data

```{r}
boreal = st_read("../outputs/boundaries/landsatScenes/selectLandsatScenes.shp", "selectLandsatScenes")
```

```{r}
ecozones = st_read("../data/spatialData/dire_ecoregs_caea/dire_ecoregs_caea.shp", "dire_ecoregs_caea")
```

```{r}
above = st_read("../data/ABoVE_Study_Domain/ABoVE_Study_Domain.shp", "ABoVE_Study_Domain")
```

# Data Attributes

```{r}
boreal
```

```{r}
unique(boreal$ECO_NAME)
```

```{r}
ecozones
```

# Reproject ecozones

```{r}
projection = st_crs(boreal)
```

```{r}
ecozones_wgs84 = st_transform(ecozones, projection)
above_wgs84 = st_transform(above, projection)
```

```{r}
ecozones_wgs84
```
# Filter Scenes to Canada

```{r}
( can = boreal %>% filter(ISO_A2 =="CA") )
```


```{r}
( join1 = st_join(can, ecozones_wgs84) )
```

```{r}
( join2 = st_join(join1, above_wgs84) )
```

```{r}
( direScenes = join2 %>% 
    st_drop_geometry() %>% 
    drop_na(NA_L2NAME) %>% 
    dplyr::select(PATH, ROW, PR, ECO_NAME, NA_L2NAME, Region) %>% 
    filter(!duplicated(PR))
  )
```

```{r}
write.csv(direScenes, '../outputs/landsatScenes/2025-05-14_CanadaDIREPriorityABoVERegion.csv', row.names=F)
```


# Map View
```{r}
( NWT_scenes = join2 %>% 
    drop_na(NA_L2NAME) %>% 
    dplyr::select(PATH, ROW, PR, ECO_NAME, NA_L2NAME, Region) %>% 
    filter(!duplicated(PR)) %>%
    filter(Region == "Core Region") %>%
    filter(ECO_NAME == "Northwest Territories taiga")
  )
```

```{r}
( NCST_scenes = join2 %>% 
    drop_na(NA_L2NAME) %>% 
    dplyr::select(PATH, ROW, PR, ECO_NAME, NA_L2NAME, Region) %>% 
    filter(!duplicated(PR)) %>%
    filter(Region == "Core Region") %>%
    filter(ECO_NAME == "Northern Canadian Shield taiga")
  )
```

```{r}
mapview( NWT_scenes)
```
```{r}
st_write(NCST_scenes, "../outputs/LS_scenes/NCST_Above_scenes.shp", driver = "ESRI Shapefile", append = FALSE)
```

```{r}
st_write(NWT_scenes, "../outputs/LS_scenes/NWT_Above_scenes.shp", driver = "ESRI Shapefile", append = FALSE)
```

```{r}
NWT_scenes_df =  NWT_scenes %>% st_drop_geometry()
```

```{r}
NCST_scenes_df =  NCST_scenes %>% st_drop_geometry()
```

```{r}
write.csv(NCST_scenes_df, '../outputs/landsatScenes/2025-05-28_NCSTABoVERegionScenes.csv', row.names=F)
```

```{r}
write.csv(NWT_scenes_df, '../outputs/landsatScenes/2025-05-28_NWTABoVERegionScenes.csv', row.names=F)
```


