---
title: "DELET??? LST Point Organize"
author: "Anna Talucci"
date: "2024-02-27"
output: html_document
---

# Packages
```{r}
library(tidyverse)
library(sf)
```

# Data

```{r}
sklst1k = read_csv("../data/samplePoints/raw/sk/skLSTSummer2013To2018.csv") %>% dplyr::select(-.geo)
```

```{r}
sklst1k
```
```{r}
skreburn1k = read_csv("../data/samplePoints/raw/sk/skReburn1000v2.csv") %>% dplyr::select(-.geo)
```
```{r eval=FALSE, include=FALSE}
## Code revision for below code from chat gpt
library(dplyr)
library(readr)

# Read Data
sklst1k <- read_csv("../data/samplePoints/raw/sk/skLSTSummer2013To2018.csv") %>% select(-.geo)
skreburn1k <- read_csv("../data/samplePoints/raw/sk/skReburn1000v2.csv") %>% select(-.geo)

# Clean Data
lstclean <- sklst1k %>%
  full_join(skreburn1k, by = c("system:index", "ECO_NAME", "lat", "lon", "rowId")) %>%
  rename(ID = "system:index", countYr = count.x, water = water.x, maxYr = maxCA, 
         medianYr = medianCA, minYr = minCA, sumYr = sumCA) %>%
  mutate(across(c(maxYr, medianYr, minYr, sumYr), ~replace_na(., 0))) %>%
  select(ID:rowId, maxYr:sumYr, water) %>%
  mutate(
    burned = case_when(
      countYr == 0 ~ "Unburned",
      countYr == 1 ~ "One",
      countYr == 2 ~ "Two",
      countYr == 3 ~ "Three",
      TRUE ~ "Other"
    )
  ) %>%
  mutate(across(2013:2018, ~2018 - maxYr, .names = "TSF{col}")) %>%
  mutate(across(2013:2018, ~case_when(
    countYr == 0 ~ "0",
    . == 1 ~ "1",
    . %in% 2:5 ~ "2-5",
    . %in% 6:10 ~ "6-10",
    . %in% 11:20 ~ "11-20",
    . %in% 21:31 ~ "21-31",
    TRUE ~ "Other"
  ), .names = "TimeSinceFire{col}")) %>%
  mutate(across(starts_with("TimeSinceFire"), ~ordered(., levels = c("0", "1", "2-5", "6-10", "11-20", "21-31", "Other"))),
         burned = ordered(burned, levels = c("Unburned", "One", "Two", "Three", "Other"))) %>%
  filter(water == 1, lat >= 55)

# Function to Create Yearly Data
create_samp_df <- function(year, data) {
  data %>%
    select(ID, ECO_NAME, !!sym(paste0("lst", year)), countYr:sumYr, burned, !!sym(paste0("TSF", year)), !!sym(paste0("TimeSinceFire", year))) %>%
    rename(lst = !!sym(paste0("lst", year)), TSF = !!sym(paste0("TSF", year)), TimeSinceFire = !!sym(paste0("TimeSinceFire", year))) %>%
    mutate(lstYr = year, tsfYr = year)
}

# Generate Data Frames for Each Year and Bind Rows
years <- 2013:2018
sklstdata1k <- bind_rows(lapply(years, create_samp_df, data = lstclean)) %>%
  mutate(shldPln = ifelse(ECO_NAME == "Mid-Canada Boreal Plains forests", "Plains", "Shield"))

# Export
write.csv(sklstdata1k, '../outputs/cleanedSamplePoints/skStratifiedSample1k20182013LST.csv', row.names = FALSE)

```


# Clean
```{r}
( lstclean = sklst1k %>% 
  full_join(., skreburn1k, by=c("system:index", "ECO_NAME", "lat", "lon", "rowId")) %>%
  rename(ID = "system:index", countYr = count.x, water = water.x, maxYr=maxCA, medianYr=medianCA, minYr=minCA, sumYr=sumCA) %>%
  mutate_at(c('maxYr', 'medianYr', 'minYr', 'sumYr'), ~replace_na(.,0)) %>%
  dplyr::select(ID:rowId, maxYr:sumYr, water) %>%
  mutate(burned = ifelse(countYr==0, "Unburned",
                  ifelse(countYr==1, "One",
                  ifelse(countYr==2, "Two",
                  ifelse(countYr==3, "Three", "other"))))) %>%
  mutate(TSF2018 = 2018-maxYr,
         TSF2017 = 2017-maxYr,
         TSF2016 = 2016-maxYr,
         TSF2015 = 2015-maxYr,
         TSF2014 = 2014-maxYr,
         TSF2013 = 2013-maxYr) %>%
    mutate(TimeSinceFire2018 = ifelse(countYr==0, "0",
                               ifelse(TSF2018==1, "1",
                               ifelse(TSF2018 %in% c(2, 3, 4, 5), "2-5",
                              ifelse(TSF2018 %in% c(6, 7, 8, 9, 10), "6-10", 
                              ifelse(TSF2018 %in% c(10:19), "11-20", 
                               ifelse(TSF2018 %in% c(20:31), "21-31", "Other")))))))  %>% 
  mutate(TimeSinceFire2017 = ifelse(countYr==0, "0",
                               ifelse(TSF2017==1, "1",
                               ifelse(TSF2017 %in% c(2, 3, 4, 5), "2-5",
                              ifelse(TSF2017 %in% c(6, 7, 8, 9, 10), "6-10", 
                              ifelse(TSF2017 %in% c(10:19), "11-20", 
                               ifelse(TSF2017 %in% c(20:31), "21-31", "Other")))))))  %>% 
  mutate(TimeSinceFire2016 = ifelse(countYr==0, "0",
                               ifelse(TSF2016==1, "1",
                               ifelse(TSF2016 %in% c(2, 3, 4, 5), "2-5",
                              ifelse(TSF2016 %in% c(6, 7, 8, 9, 10), "6-10", 
                              ifelse(TSF2016 %in% c(10:19), "11-20", 
                               ifelse(TSF2016 %in% c(20:31), "21-31", "Other")))))))  %>% 
  mutate(TimeSinceFire2015 = ifelse(countYr==0, "0",
                               ifelse(TSF2015==1, "1",
                               ifelse(TSF2015 %in% c(2, 3, 4, 5), "2-5",
                              ifelse(TSF2015 %in% c(6, 7, 8, 9, 10), "6-10", 
                              ifelse(TSF2015 %in% c(10:19), "11-20", 
                               ifelse(TSF2015 %in% c(20:31), "21-31", "Other")))))))  %>% 
  mutate(TimeSinceFire2014 = ifelse(countYr==0, "0",
                               ifelse(TSF2014==1, "1",
                               ifelse(TSF2014 %in% c(2, 3, 4, 5), "2-5",
                              ifelse(TSF2014 %in% c(6, 7, 8, 9, 10), "6-10", 
                              ifelse(TSF2014 %in% c(10:19), "11-20", 
                               ifelse(TSF2014 %in% c(20:31), "21-31", "Other")))))))  %>% 
  mutate(TimeSinceFire2013 = ifelse(countYr==0, "0",
                               ifelse(TSF2013==1, "1",
                               ifelse(TSF2013 %in% c(2, 3, 4, 5), "2-5",
                              ifelse(TSF2013 %in% c(6, 7, 8, 9, 10), "6-10", 
                              ifelse(TSF2013 %in% c(10:19), "11-20", 
                               ifelse(TSF2013 %in% c(20:31), "21-31", "Other")))))))  %>% 
  mutate(TimeSinceFire2018= ordered(TimeSinceFire2018, levels = c("0", "1", "2-5", "6-10", "11-20", "21-31", "Other")),
         TimeSinceFire2017= ordered(TimeSinceFire2017, levels = c("0", "1", "2-5", "6-10", "11-20", "21-31", "Other")),
         TimeSinceFire2016= ordered(TimeSinceFire2016, levels = c("0", "1", "2-5", "6-10", "11-20", "21-31", "Other")),
         TimeSinceFire2015= ordered(TimeSinceFire2015, levels = c("0", "1", "2-5", "6-10", "11-20", "21-31", "Other")),
         TimeSinceFire2014= ordered(TimeSinceFire2014, levels = c("0", "1", "2-5", "6-10", "11-20", "21-31", "Other")),
         TimeSinceFire2013= ordered(TimeSinceFire2013, levels = c("0", "1", "2-5", "6-10", "11-20", "21-31", "Other")),
         burned = ordered(burned, levels = c("Unburned", "One", "Two", "Three", "other"))) %>%
  filter(water==1) %>%
  filter(lat >=55)
)
```


## Reorganize 
```{r}
( 
  samp2018k = 
    lstclean %>% 
    dplyr::select(ID, ECO_NAME, lst2018, countYr:sumYr, burned, TSF2018, TimeSinceFire2018) %>%
    rename(lst=lst2018, TSF = TSF2018, TimeSinceFire=TimeSinceFire2018) %>%
    mutate(lstYr=2018,
           tsfYr=2018)
)
```

```{r}
( 
  samp2017k = 
    lstclean %>% 
    dplyr::select(ID, ECO_NAME, lst2017, countYr:sumYr, burned, TSF2017, TimeSinceFire2017) %>%
    rename(lst=lst2017, TSF = TSF2017, TimeSinceFire=TimeSinceFire2017) %>%
    mutate(lstYr=2017,
           tsfYr=2017)
)
```

```{r}
( 
  samp2016k = 
    lstclean %>% 
    dplyr::select(ID, ECO_NAME, lst2016, countYr:sumYr, burned, TSF2016, TimeSinceFire2016) %>%
    rename(lst=lst2016, TSF = TSF2016, TimeSinceFire=TimeSinceFire2016) %>%
    mutate(lstYr=2016,
           tsfYr=2016)
)
```

```{r}
( 
  samp2015k = 
    lstclean %>% 
    dplyr::select(ID, ECO_NAME, lst2015, countYr:sumYr, burned, TSF2015, TimeSinceFire2015) %>%
    rename(lst=lst2015, TSF = TSF2015, TimeSinceFire=TimeSinceFire2015) %>%
    mutate(lstYr=2015,
           tsfYr=2015)
)
```

```{r}
( 
  samp2014k = 
    lstclean %>% 
    dplyr::select(ID, ECO_NAME, lst2014, countYr:sumYr, burned, TSF2014, TimeSinceFire2014) %>%
    rename(lst=lst2014, TSF = TSF2014, TimeSinceFire=TimeSinceFire2014) %>%
    mutate(lstYr=2014,
           tsfYr=2014)
)
```

```{r}
( 
  samp2013k = 
    lstclean %>% 
    dplyr::select(ID, ECO_NAME, lst2013, countYr:sumYr, burned, TSF2013, TimeSinceFire2013) %>%
    rename(lst=lst2013, TSF = TSF2013, TimeSinceFire=TimeSinceFire2013) %>%
    mutate(lstYr=2013,
           tsfYr=2013)
)
```

```{r}

(
  sklstdata1k =
    bind_rows(samp2018k, samp2017k, samp2016k, samp2015k, samp2014k, samp2013k) %>%
    mutate(shldPln = ifelse(ECO_NAME=="Mid-Canada Boreal Plains forests", "Plains", "Shield"))
)
```
```{r}
unique(skdata1k$ECO_NAME)
skdata1k %>% filter(ECO_NAME=="Northern Canadian Shield taiga" ) 
```

```{r}
write.csv(skdata1k, '../outputs/cleanedSamplePoints/skStratifiedSample1k20182013LST.cvs', row.names=F)
```
