---
title: "Select Landsat Scenes"
author: "Anna Talucci"
date: "2024-04-22"
output: html_document
---

# Overview
Select Landsat scenes of interest for other reburn areas. 

Exclude military base areas in AK


# Packages
```{r}
library(sf)
library(tidyverse)
library(terra)
library(magrittr)
library(pacman)
library(ggnewscale)
library(scales)
```

# Data 
## Federal Lands
```{r}
fed = st_read("../data/boundaries/USA_Federal_Lands/USA_Federal_Lands.shp", "USA_Federal_Lands")
```

## Landsat scenes
```{r}
scenes = st_read("../data/boundaries/WRS2_descending_0/WRS2_descending.shp", "WRS2_descending")
```


```{r}
wrld = st_read("../data/boundaries/world/WB_countries_Admin0_10m.shp", "WB_countries_Admin0_10m")
```

## Resolve
```{r}
resolve = st_read("../data/boundaries/RESOLVE_Ecoregions_and_Biomes/Biomes_and_Ecoregions_2017.shp", "Biomes_and_Ecoregions_2017")
```


    
# Data Structure

```{r}
glimpse(fed)
glimpse(scenes)
glimpse(wrld)
glimpse(resolve)
```

```{r}
unique(fed$ADMIN1)
unique(wrld$SUBREGION)
```

# Select Polygons

## Fed select AK

```{r}
( akFed = fed %>% filter(STATE=="AK") %>% filter(ADMIN1 != "DOD"))

```

```{r}
unique(akFed$ADMIN1)
```


## World NA

```{r}
( northAm = wrld %>% filter(SUBREGION=="Northern America") %>% filter(FORMAL_EN %in% c("United States of America", "Canada")))
```

```{r}
unique(akFed$ADMIN1)
```

## Resolve
```{r}
( boreal = resolve %>% 
    filter(REALM %in% c("Nearctic")) %>% 
    dplyr::select(OBJECTID, ECO_NAME, BIOME_NUM, BIOME_NAME, REALM, ECO_ID, geometry) %>% 
    filter(BIOME_NUM %in% c(6)) 
)
```

# Instersection of Scenes with North America

```{r}
( join1 = st_join(scenes, northAm) )
```

```{r}
( scenesNA = join1 %>% filter(FORMAL_EN%in% c("United States of America", "Canada")) %>% dplyr::select(AREA:REGION_WB, Shape_Leng:geometry) %>% filter(ROW<=30) %>% filter(ROW>=10))
```

```{r}
( join2 = st_join(scenesNA, boreal) )
```

```{r}
(borealNA = join2 %>% drop_na(BIOME_NUM))
```

# Check

## LAndsat scene info
```{r}
n_distinct(scenesNA$PR)
n_distinct(borealNA$PR)
```

## Map check 

### North America
```{r}
ggplot() +
     geom_sf(data = northAm, fill = "#F9F6EE", colour="#A9AB9D") +
  geom_sf(data = scenesNA, fill = NA, color="black") +
  coord_sf() +
  theme_bw()
```


### Boreal North America
```{r}
ggplot() +
     geom_sf(data = northAm, fill = "#F9F6EE", colour="#A9AB9D") +
  geom_sf(data = borealNA, fill = NA, color="black") +
  coord_sf() +
  theme_bw()
```

# Save shapefile
```{r eval=FALSE, include=FALSE}
st_write(borealNA, "../outputs/boundaries/landsatScenes/selectLandsatScenes.shp", driver="ESRI Shapefile")
```



